main: net.mmgmc.eup.Main
name: Extra-Utilities-Plugin
api-version: 1.16
version: 1.0.0
softdepend: [PlaceholderAPI]

commands:
    eup:
        description: Base command for Extra-Utilities-Plugin.
    discord:
        description: Provides the discord link.
    vote:
        description: Provides a list of links you can use to vote.
    reloadeup:
        description: Reloads the config file.
    motd:
        description: Displays the MOTD.
    skull:
        description: Gives sender a custom skull.

permissions:
    eup.eup:
        description: Allows sender to use the base command.
    eup.help:
        description: Allows sender to see the list of commands.
    eup.reload:
        description: Allows sender to reload config.yml
    eup.motd:
        description: Allows sender to read the MOTD
    eup.vote:
        description: Allows sender to read the vote list
    eup.skull:
        description: Allows sender to recieve a custom skull.